In [2]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, Polygon

%matplotlib inline

In [4]:
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

In [6]:
from geopy.geocoders import Nominatim

## Shapefile
- The major file format for geographic data
- usually downloaded as zip file

1. shp - shapefile - actual geometry of file
2. dbf - database file - additional info outside of the shape
3. prj - projection file - gives all the assumptions about earth we are making like area
4. shx - index file - basically makes shp file a little bit faster
. 
. 
.

In [8]:
states = gpd.read_file("Data/ne_10m_populated_places.shp")
states.head()

,SCALERANK,NATSCALE,LABELRANK,FEATURECLA,NAME,NAMEPAR,NAMEALT,NAMEASCII,ADM0CAP,CAPIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
0,10,1,8.0,Admin-1 capital,Colonia del Sacramento,None,None,Colonia del Sacramento,0,None,...,None,None,None,None,None,None,None,None,None,POINT (-57.83612 -34.46979)
1,10,1,8.0,Admin-1 capital,Trinidad,None,None,Trinidad,0,None,...,None,None,None,None,None,None,None,None,None,POINT (-56.90100 -33.54400)
2,10,1,8.0,Admin-1 capital,Fray Bentos,None,None,Fray Bentos,0,None,...,None,None,None,None,None,None,None,None,None,POINT (-58.30400 -33.13900)
3,10,1,8.0,Admin-1 capital,Canelones,None,None,Canelones,0,None,...,None,None,None,None,None,None,None,None,None,POINT (-56.28400 -34.53800)
4,10,1,8.0,Admin-1 capital,Florida,None,None,Florida,0,None,...,None,None,None,None,None,None,None,None,None,POINT (-56.21500 -34.09900)